---
layout:                                 post

title:                                  Welcome to Jekyll!
tagline:                                Jekyll For Everyone
# date:                                 2022-12-24 09:33:20 +0000

categories:                             [ Jekyll ]
tags:                                   [ Theme ]

image:
  path:                                 /assets/images/modules/attics/1920x1280/nick-fewings.jpg
  width:                                1920
  height:                               1280
  alt:                                  Photo by Nick Fewings on Unsplash

fab_menu_id:                            default
comments:                               false
scrollbar:                              false
regenerate:                             false

resources:                              [ animate ]
resource_options:
  - attic:
      opacity:                          0.5
      slides:
        - url:                          /assets/images/modules/attics/1920x1280/nick-fewings.jpg
          alt:                          Photo by Nick Fewings on Unsplash
          alignY:                       0.3
          badge:
            type:                       unsplash
            author:                     Nick Fewings
            href:                       https://unsplash.com/@jannerboy62
---

// Page Initializer
// =============================================================================
// Enable the Liquid Preprocessor
:page-liquid:

// Set (local) page attributes here
// -----------------------------------------------------------------------------
// :page--attr:                         <attr-value>

[role="dropcap"]
Nunc id malesuada nisl, in tincidunt sapien. Sed cursus nibh vitae fermentum
efficitur. Mauris non lectus nisi. Morbi euismod eros vitae sagittis pretium.
Etiam sed lectus ac ex rutrum maximus at a dolor. Vestibulum molestie et risus
nec sodales.

excerpt__end

//  Load Liquid procedures
// -----------------------------------------------------------------------------
{% capture load_attributes %}themes/{{site.template.name}}/procedures/global/attributes_loader.proc{%endcapture%}

// Load page attributes
// -----------------------------------------------------------------------------
{% include {{load_attributes}} scope="global" %}


// Page content
// ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

// Include sub-documents (if any)
// -----------------------------------------------------------------------------
You’ll find this post in your `_posts` directory. Go ahead and edit it and
re-build the site to see your changes. You can rebuild the site in many
different ways, but the most common way is to run `jekyll serve`, which
launches a web server and auto-regenerates your site when a file is updated.

Jekyll requires blog post files to be named according to the following format:

`YEAR-MONTH-DAY-title.MARKUP`

Where `YEAR` is a four-digit number, `MONTH` and `DAY` are both two-digit
numbers, and `MARKUP` is the file extension representing the format used in
the file. After that, include the necessary front matter. Take a look at the
source for this post to get an idea about how it works.

Jekyll also offers powerful support for code snippets:

[source, ruby]
----
def print_hi(name)
  puts "Hi, #{name}"
end
print_hi('Tom')
#=> prints 'Hi, Tom' to STDOUT.
----

Check out the https://jekyllrb.com/docs/home[Jekyll Docs, {{browser-window--new}}]
for more info on how to get the most out of Jekyll. File all bugs amd feature
requests at https://github.com/jekyll/jekyll/issues[Jekyll Github Project, {{browser-window--new}}].
If you have questions, you can ask them on
https://talk.jekyllrb.com/[Jekyll Talk, {{browser-window--new}}].
